### ISSUE TITLE
ci/coverage.sh is broken on AWS

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#403]
cc: #398

```
ore::ops::index::IndexMut<I> for [T]>::index_mut':
--
  | /checkout/src/libcore/slice/mod.rs:778: undefined reference to `<core::ops::range::RangeFull as core::slice::SliceIndex<[T]>>::index_mut'
  | /solana/target/debug/deps/solana-e479d614c684f746.29iy2rpwe8zy8cyi.rcgu.o: In function `core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut':
  | /checkout/src/libcore/slice/mod.rs:778: undefined reference to `<core::ops::range::RangeFull as core::slice::SliceIndex<[T]>>::index_mut'
  | /solana/target/debug/deps/solana-e479d614c684f746.2ftx62vmjux0jz57.rcgu.o: In function `solana::write_stage::WriteStage::new_drain':
  | /solana/src/write_stage.rs:60: undefined reference to `std::thread::Builder::spawn'
  | /solana/target/debug/deps/solana-e479d614c684f746.4cdw7ghqmqpreqbn.rcgu.o: In function `<&'a T as core::fmt::Debug>::fmt':
  | /checkout/src/libcore/fmt/mod.rs:1768: undefined reference to `<solana::mint::Mint as core::fmt::Debug>::fmt'
  | /usr/bin/ld: /solana/target/debug/deps/solana-e479d614c684f746: hidden symbol `_ZN90_$LT$core..ops..range..RangeFull$u20$as$u20$core..slice..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$9index_mut17hbc92bcc287064735E' isn't defined
  | /usr/bin/ld: final link failed: Bad value
  | collect2: error: ld returned 1 exit status
```

:face_with_head_bandage:

**Comment by mvines** [comment]
Note to self, revert #409 as a part of fixing this issue

**Comment by mvines** [comment]
Fixed
