### ISSUE TITLE
Inline assembly is not supported in Solana programs

### ISSUE THREAD

**Issue by skynetcapital** [solana-labs/solana#18848]
#### Problem
While learning Anchor and thinking about compute unit optimizations, I noticed that this Anchor program fails to build, with the following message: `error[E0472]: asm! is unsupported on this target`
```
#![feature(asm)]
use anchor_lang::prelude::*;

#[program]
mod basic_0 {
    use super::*;
    pub fn initialize(_ctx: Context<Initialize>) -> ProgramResult {
        let mut x: u64 = 5 + 8;
        assert_eq!(x, 8);
        Ok(())
    }

    pub fn initialize2(_ctx: Context<Initialize>) -> ProgramResult {
        #![feature(asm)]
        let mut x: u64 = 3;
        unsafe {
            asm!("add {0}, {number}", inout(reg) x, number = const 5);
        }
        assert_eq!(x, 8);
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

#### Proposed Solution
Investigate if inline rust assembly is safe (and beneficial) to support in Solana/bpf

**Comment by skynetcapital** [comment]
@dmakarov has requested assignment of this issue.

**Comment by dmakarov** [comment]
This should be resolved after we upgrade our rust toolchain to rust 1.54.0.

**Comment by t-nelson** [comment]
> This should be resolved after we upgrade our rust toolchain to rust 1.54.0.

I'm working on taking rust stable to 1.54, nightly 2021-08-02

**Comment by dmakarov** [comment]
> > This should be resolved after we upgrade our rust toolchain to rust 1.54.0.
> 
> I'm working on taking rust stable to 1.54, nightly 2021-08-02

This is great, but I mean our rust to bpf compiler need to be based on rustc 1.54.0 source, which added support of inline asm for the bpf target. :-)

**Comment by t-nelson** [comment]
> This is great, but I mean our rust to bpf compiler need to be based on rustc 1.54.0 source, which added support of inline asm for the bpf target. :-)

Oh!  Haha. I thought I already saw that in the works, which is what motivated me to get the monorepo bumped :laughing:

**Comment by dmakarov** [comment]
Fixed in #19117
