### PR TITLE
Removes unnecessary mut

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

There are unnecessary mutable variables that clippy will complain about when upgrading Rust to 1.71.0

```
warning: variable does not need to be mutable
  --> sdk/program/src/message/compiled_keys.rs:43:17
   |
43 |             let mut meta = key_meta_map.entry(ix.program_id).or_default();
   |                 ----^^^^
   |                 |
   |                 help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default
```

#### Summary of Changes

Remove unnecessary `mut`

### CODE REVIEW

**Review by bw-solana — APPROVED** [review]
LGTM!

File: sdk/program/src/message/compiled_keys.rs [hunk 1]
```diff
@@ -49,7 +49,7 @@ impl CompiledKeys {
             }
         }
         if let Some(payer) = &payer {
-            let mut meta = key_meta_map.entry(*payer).or_default();
+            let meta = key_meta_map.entry(*payer).or_default();
             meta.is_signer = true;
             meta.is_writable = true;
```
Comment (ilya-bobyr) [inline sdk/program/src/message/compiled_keys.rs:54]: How can this work without a `mut`? :|
Seems like a false positive to me: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fa3e6986a1fac2feb7bd38496fa5aced
Does CI check compilation errors for `sdk/program`?

This warning found false positives (that were also incorrectly updated) in the other repo that I was just fixing.
