### PR TITLE
Fix `solana-address-lookup-table-program` compilation

### LINKED ISSUE #34352: `solana-address-lookup-table-program` compile error in program environment
#### Problem

`solana-address-lookup-table-program ^1.17` is broken in programs after https://github.com/solana-labs/solana/pull/33165.

It uses `solana_sdk` crate instead of `solana_program` which cause compile errors for programs:

https://github.com/solana-labs/solana/blob/6f2b3bbad38f8360efb7272324d487cfd4b9f48e/programs/address-lookup-table/src/lib.rs#L7-L15

```
   Compiling solana-address-lookup-table-program v1.17.0
error[E0433]: failed to resolve: use of undeclared crate or module `solana_sdk`
  --> src/lib.rs:11:9
   |
11 | pub use solana_sdk::address_lookup_table::{
   |         ^^^^^^^^^^ use of undeclared crate or module `solana_sdk`
```

To be specific, the above error is about `solana-sdk` is not being declared as a dependency in program environment but it would still fail if it was declared:

https://github.com/solana-labs/solana/blob/6f2b3bbad38f8360efb7272324d487cfd4b9f48e/programs/address-lookup-table/Cargo.toml#L24-L26

#### Proposed Solution

Export it from `solana-program` instead of `solana-sdk` for program compilation.

### PR DESCRIPTION
**Pull request by acheroncrypto**
#### Problem

`solana-address-lookup-table-program` crate causes compile errors in programs after https://github.com/solana-labs/solana/pull/33165

Problem explained in more detail in #34352

#### Summary of Changes

- Add `#[cfg(target_os = "solana")]` checks to decide which SDK crate to use
- Make `processor` module only available in non-program environments

Fixes #34352

### CODE REVIEW

File: programs/address-lookup-table/src/lib.rs [hunk 1]
```diff
@@ -13,3 +15,14 @@ pub use solana_sdk::address_lookup_table::{
     program::{check_id, id, ID},
     state,
 };
+
+#[cfg(target_os = "solana")]
+#[deprecated(
+    since = "1.17.0",
+    note = "Please use `solana_program::address_lookup_table` instead"
+)]
```
Comment (acheroncrypto) [inline programs/address-lookup-table/src/lib.rs:23]: The `#[deprecated]` attribute doesn't seem to be doing anything for `use` statements as I don't get any warnings about depreciation for these re-exports. Still, it could be useful to see it when looking at the source code.

**Review by joncinque — COMMENTED** [review]
Thanks for noticing and fixing! I agree that it's best to just re-export from `solana_program` -- would you mind making that change too?

Also, I imagine this needs to be backported to 1.17, correct?

**Comment by acheroncrypto** [comment]
> Thanks for noticing and fixing!

Thanks for the review!

> Also, I imagine this needs to be backported to 1.17, correct?

Yes, all releases since `1.17.0` have this problem.

**Review by joncinque — APPROVED** [review]
Thanks for taking care of this, and sorry for the breakage!
