### ISSUE TITLE
package.json references `index.browser.cjs.js` which does not exist

### ISSUE THREAD

**Issue by venables** [solana-labs/solana#23494]
#### Problem

Pull Request #21940 introduced a bug where package.json points to a file that does not exist in the `browser` `./lib/index.cjs.js` field.

While trying to use this library in an environment such as react-native, you see the following error:

```
While trying to resolve module `@solana/web3.js` from file `...`, the package `.../node_modules/@solana/web3.js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`.../node_modules/@solana/web3.js/lib/index.browser.cjs.js`.
```

#### Proposed Solution

Revert #21940 or update rollup config to output a .browser.cjs.js file.

**Comment by mcintyre94** [comment]
I think I just hit this issue, installing 1.35.1 instead worked. When I installed 1.36.0 I got this error:

```
error: Error: While trying to resolve module `@solana/web3.js` from file `/Users/callummcintyre/projects/SolDevWallet/components/HomeScreen.tsx`, the package `/Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js`. Indeed, none of these files exist:

  * /Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.json|.native.json|.json)
  * /Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js/index(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.json|.native.json|.json)
    at DependencyGraph.resolveDependency (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/node-haste/DependencyGraph.js:311:17)
    at Object.resolve (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 2)
    at async processModule (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:198:5)
```

**Comment by mcintyre94** [comment]
I think I've just hit this - I'm seeing errors using v1.35.1 or v1.36.0 in react-native. v1.35.0 works correctly.

```
error: Error: While trying to resolve module `@solana/web3.js` from file `/Users/callummcintyre/projects/SolDevWallet/components/HomeScreen.tsx`, the package `/Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js`. Indeed, none of these files exist:

  * /Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.json|.native.json|.json)
  * /Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js/index(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.json|.native.json|.json)
    at DependencyGraph.resolveDependency (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/node-haste/DependencyGraph.js:311:17)
    at Object.resolve (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 2)
```

**Comment by jordansexton** [comment]
Should be fixed by #21940. Please comment if it isn't!

**Comment by venables** [comment]
@jordansexton that PR actually introduced the bug, it is not fixed.

**Comment by jordansexton** [comment]
Oops, wrong PR link! Fixed by https://github.com/solana-labs/solana/pull/23500

**Comment by sirimiri13** [comment]
> I think I've just hit this - I'm seeing errors using v1.35.1 or v1.36.0 in react-native. v1.35.0 works correctly.
> 
> ```
> error: Error: While trying to resolve module `@solana/web3.js` from file `/Users/callummcintyre/projects/SolDevWallet/components/HomeScreen.tsx`, the package `/Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js`. Indeed, none of these files exist:
> 
>   * /Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.json|.native.json|.json)
>   * /Users/callummcintyre/projects/SolDevWallet/node_modules/@solana/web3.js/lib/index.browser.cjs.js/index(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.json|.native.json|.json)
>     at DependencyGraph.resolveDependency (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/node-haste/DependencyGraph.js:311:17)
>     at Object.resolve (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/lib/transformHelpers.js:129:24)
>     at resolve (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
>     at /Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
>     at Array.reduce (<anonymous>)
>     at resolveDependencies (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
>     at processModule (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async addDependency (/Users/callummcintyre/projects/SolDevWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
>     at async Promise.all (index 2)
> ```

have you fixed it ?

**Comment by jordansexton** [comment]
This has been fixed in master but not released yet due to an unrelated CI issue. I'll try to get that resolved tomorrow.

**Comment by retf** [comment]
same issue here!
@solana/web3.js/lib/index.browser.cjs.js`. Indeed, none of these files exist

**Comment by jordansexton** [comment]
This should be fixed in v1.37.0 which has been released on NPM.

**Comment by techyNonso** [comment]
I am having similar issues and I've tried both version 1.37.0 and 1 40.0 and all show errors

**Comment by techyNonso** [comment]
It says it's missing a .cjs file and also main.js is missing

**Comment by bmeeder22** [comment]
This issue was reintroduced in `1.40.0`, was working in `1.39.0`

**Comment by bmeeder22** [comment]
Error: Cannot find module '/home/runner/work/phantasia-solana-program/phantasia-solana-program/interface/node_modules/@solana/web3.js/lib/index.cjs.js'. Please verify that the package.json has a valid "main" entry

**Comment by CriesofCarrots** [comment]
@techyNonso , @bmeeder22 : https://github.com/solana-labs/solana/issues/24689#issuecomment-1109975465
