### PR TITLE
Change get_pubkeys to match the new enum

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
Bad merges caused function to cause compilation errors

#### Summary of Changes

Fixes #

### CODE REVIEW

File: runtime/src/builtins.rs [hunk 1]
```diff
@@ -210,21 +210,16 @@ pub fn get_pubkeys() -> Vec<Pubkey> {
...
+        BuiltinFeatureTransition::Add {
+            builtin,
+            feature_id: _,
+        } => Some(builtin.id),
+        BuiltinFeatureTransition::RemoveOrRetain {
+            previously_added_builtin: _,
+            addition_feature_id: _,
+            removal_feature_id: _,
+        } => None,
+    }));
```
Comment (brooksprumo) [inline runtime/src/builtins.rs:223]: nit: Can these match patterns be simplified?

```suggestion
    pubkeys.extend(builtins.feature_transitions.iter().filter_map(|f| match f {
        BuiltinFeatureTransition::Add { builtin, .. } => Some(builtin.id),
        BuiltinFeatureTransition::RemoveOrRetain { .. } => None,
    }));
```

Note: I did not try to compile the suggestion above 😅

**Review by brooksprumo — DISMISSED** [review]
Looks good, just the one nit. No need to get another approval if you simplify the match patterns.

**Comment by brooksprumo** [comment]
Since this PR fixes the broken build on `master`, I'm merging early (one `coverage` succeeds).
