### PR TITLE
Add checks when constructing a BankSnapshotInfo from a directory 

### PR DESCRIPTION
**Pull request by xiangzhu70**
#### Problem
Before constructing a bank from a snapshot, we need to read the snapshot directories and find the highest correct one with the necessary meta info files.  Sometimes a directory may have partial information, not fully ready to be used for bank construction.  Only the ones passing the checks will be selected.

#### Summary of Changes
Add snapshot version into BankSnapshotInfo, fill that from the version file;
Add checks to ensure only a correct directory is used to generate a BankSnapshotInfo. 
A function to find the one with the highest slot, which is a wrapper of get_bank_snapshots and selecting the highest one.
Add the test function test_get_highest_bank_snapshot.  It removes the meta files in the directories, and check if it gets the highest correct snapshot.

This is one of the split PRs of https://github.com/solana-labs/solana/pull/28745.  It precedes https://github.com/solana-labs/solana/pull/30171

Fixes #

### CODE REVIEW

**Comment by xiangzhu70** [comment]
> For fastboot, we'll always need the complete accounts state in order to actually boot from that bank snapshot later. I'm not sure I understand the problem that's being solved here; `get_highest_bank_snapshot()` already gets us this information.

In https://github.com/solana-labs/solana/pull/30171 I follow the archiving path to get a full snapshot and an incremental snapshot.  This is part of that PR.  I thought it might be better that I split these parts into a small PR.

**Comment by xiangzhu70** [comment]
> > For fastboot, we'll always need the complete accounts state in order to actually boot from that bank snapshot later. I'm not sure I understand the problem that's being solved here; `get_highest_bank_snapshot()` already gets us this information.
> 
> In #30171 I follow the archiving path to get a full snapshot and an incremental snapshot. This is part of that PR. I thought it might be better that I split these parts into a small PR.

Discussed with @brooksprumo offline.  He said " An incremental snapshot is only possible as an archive. As a bank snapshot, I don't see this being a good idea because then this bank snapshot could not be used for fastboot.".  I'd like to double check with @jeffwashington and @apfitzge, because I recall some mentioning of an incremental snapshot before.

If we all agreed that a bank snapshot directory is always a full snapshot, then I will remove all the incremental snapshot directory logic from https://github.com/solana-labs/solana/pull/30171 and this PR.

File: runtime/src/snapshot_utils.rs [hunk 1]
```diff
@@ -1529,6 +1570,39 @@ fn streaming_unarchive_snapshot(
         .collect()
 }
 
+/// BankSnapshotInfo::new_from_dir() requires a few meta files to accept a snapshot dir
+/// as a valid one.  A dir unpacked from an archive lacks these files.  Fill them here to
+/// allow new_from_dir() checks to pass.  These checks are not needed for unpacked dirs,
+/// but it is not clean to add another flag to new_from_dir() to skip them.
+fn fill_snapshot_meta_files_for_unchived_snapshot(unpack_dir: impl AsRef<Path>) -> Result<()> {
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: fixec

File: runtime/src/snapshot_utils.rs [hunk 2]
```diff
@@ -162,31 +164,52 @@ impl BankSnapshotInfo {
...
+
+        let snapshot_type: Option<BankSnapshotType> = if bank_snapshot_pre_path.is_file() {
+            Some(BankSnapshotType::Pre)
+        } else if bank_snapshot_post_path.is_file() {
+            Some(BankSnapshotType::Post)
+        } else {
+            None
+        };
+        let snapshot_type = snapshot_type
+            .ok_or_else(|| SnapshotError::MissingSnapshotFile(bank_snapshot_dir.clone()))?;
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: good point.  updated.

File: runtime/src/snapshot_utils.rs [hunk 3]
```diff
@@ -162,31 +164,52 @@ impl BankSnapshotInfo {
...
-        None
+        let version_path = bank_snapshot_dir.join(SNAPSHOT_VERSION_FILENAME);
+        let version_str = snapshot_version_from_file(version_path)?;
+        let snapshot_version = SnapshotVersion::from_str(version_str.as_str())
+            .or(Err(SnapshotError::InvalidVersion))?;
+
+        // There is a time window from the slot directory being created, and the content being completely
+        // filled.  Check the completion to avoid using a highest found slot directory with missing content.
+        let completion_flag_file = bank_snapshot_dir.join(SNAPSHOT_STATE_COMPLETE_FILENAME);
+        if fs::metadata(completion_flag_file).is_err() {
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: fixed.

File: runtime/src/snapshot_utils.rs [hunk 4]
```diff
@@ -162,31 +164,52 @@ impl BankSnapshotInfo {
...
+        let status_cache_file = bank_snapshot_dir.join(SNAPSHOT_STATUS_CACHE_FILENAME);
+        if fs::metadata(status_cache_file).is_err() {
+            return Err(SnapshotError::MissingStatusCacheFile(bank_snapshot_dir));
         }
 
-        None
+        let version_path = bank_snapshot_dir.join(SNAPSHOT_VERSION_FILENAME);
+        let version_str = snapshot_version_from_file(version_path)?;
+        let snapshot_version = SnapshotVersion::from_str(version_str.as_str())
+            .or(Err(SnapshotError::InvalidVersion))?;
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:184]: maybe we could combine the actions to a function SnapshotVesion::from_file()

File: runtime/src/snapshot_utils.rs [hunk 5]
```diff
@@ -162,31 +164,52 @@ impl BankSnapshotInfo {
...
 
-        if bank_snapshot_post_path.is_file() {
-            return Some(BankSnapshotInfo {
-                slot,
-                snapshot_type: BankSnapshotType::Post,
-                snapshot_dir: bank_snapshot_dir,
-            });
+        let status_cache_file = bank_snapshot_dir.join(SNAPSHOT_STATUS_CACHE_FILENAME);
+        if fs::metadata(status_cache_file).is_err() {
+            return Err(SnapshotError::MissingStatusCacheFile(bank_snapshot_dir));
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: fxied

File: runtime/src/snapshot_utils.rs [hunk 6]
```diff
@@ -162,31 +164,52 @@ impl BankSnapshotInfo {
...
         }
 
-        if bank_snapshot_post_path.is_file() {
-            return Some(BankSnapshotInfo {
-                slot,
-                snapshot_type: BankSnapshotType::Post,
-                snapshot_dir: bank_snapshot_dir,
-            });
+        let status_cache_file = bank_snapshot_dir.join(SNAPSHOT_STATUS_CACHE_FILENAME);
+        if fs::metadata(status_cache_file).is_err() {
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: fixed

**Comment by xiangzhu70** [comment]
> After we've unarchived a snapshot archive, we _don't_ have a bank snapshot in the snapshots directory, so I don't understand why this is now required. Did that behavior change?

Because the snapshot from dir case and the snapshot from archive share the get_bank_snapshots() and new_from_dir() functions.  To let a BankSnapshotInfo to be returned after the directory checks in mew_from_dir, I have to make the unarchived snapshot directories contain the meta files, even they are only used in snapshot_from_dir case.

**Comment by xiangzhu70** [comment]
> I think should be split up

How should it be split up?  Among the 3 issues, #2 is really just a result of checks introduced in #3, so they should go together.  #1 is just a wrapper function which not much content.  I can either remove it (just use get_highest_bank_snapshot_pre instead, although it carries implementation assumption) or move it back to PR https://github.com/solana-labs/solana/pull/30171.  Which way do you prefer?

**Comment by xiangzhu70** [comment]
> I think to make this cleaner, the new errors should go under their own new error enum type,

It is now done.  git pushed.

File: runtime/src/snapshot_utils.rs [hunk 7]
```diff
@@ -296,7 +325,34 @@ pub enum SnapshotError {
 
     #[error("invalid AppendVec path: {}", .0.display())]
     InvalidAppendVecPath(PathBuf),
+
+    #[error("no valid snapshot dir found under {}", .0.display())]
+    NoSnapshotSlotDir(PathBuf),
+}
+#[derive(Error, Debug)]
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:332]: I was following SnapshotError, which doesn't have them.  Do we really need them?

I got compilation errors like below.
```
error[E0277]: the trait bound `std::io::Error: std::cmp::Eq` is not satisfied
   --> runtime/src/snapshot_utils.rs:335:16
    |
332 | #[derive(Error, Debug, Eq, PartialEq)]
    |                        -- in this derive macro expansion
...
335 |     Io(#[from] std::io::Error),
    |                ^^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `std::io::Error`
    |
note: required by a bound in `AssertParamIsEq`
   --> /Users/xiangzhu/.rustup/toolchains/1.67.1-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:315:31
    |
315 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `==` cannot be applied to type `std::io::Error`
   --> runtime/src/snapshot_utils.rs:335:16
    |
332 | #[derive(Error, Debug, Eq, PartialEq)]
    |                            --------- in this derive macro expansion
...
335 |     Io(#[from] std::io::Error),
    |                ^^^^^^^^^^^^^^
    |
    = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

File: runtime/src/snapshot_utils.rs [hunk 8]
```diff
@@ -296,7 +325,34 @@ pub enum SnapshotError {
...
+pub enum SnapshotNewFromDirError {
+    #[error("I/O error: {0}")]
+    Io(#[from] std::io::Error),
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:335]: The build errors after removing it showed they are used as below:

```
error[E0277]: `?` couldn't convert the error to `SnapshotNewFromDirError`
   --> runtime/src/snapshot_utils.rs:179:45
    |
179 |         if !fs::metadata(&status_cache_file)?.is_file() {
    |                                             ^ the trait `From<std::io::Error>` is not implemented for `SnapshotNewFromDirError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following other types implement trait `FromResidual<R>`:
              <std::result::Result<T, F> as FromResidual<Yeet<E>>>
              <std::result::Result<T, F> as FromResidual<std::result::Result<std::convert::Infallible, E>>>
    = note: required for `std::result::Result<BankSnapshotInfo, SnapshotNewFromDirError>` to implement `FromResidual<std::result::Result<std::convert::Infallible, std::io::Error>>`

error[E0277]: `?` couldn't convert the error to `SnapshotNewFromDirError`
   --> runtime/src/snapshot_utils.rs:195:48
    |
195 |         if !fs::metadata(&completion_flag_file)?.is_file() {
    |                                                ^ the trait `From<std::io::Error>` is not implemented for `SnapshotNewFromDirError`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following other types implement trait `FromResidual<R>`:
              <std::result::Result<T, F> as FromResidual<Yeet<E>>>
              <std::result::Result<T, F> as FromResidual<std::result::Result<std::convert::Infallible, E>>>
    = note: required for `std::result::Result<BankSnapshotInfo, SnapshotNewFromDirError>` to implement `FromResidual<std::result::Result<std::convert::Infallible, std::io::Error>>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `solana-runtime` due to 2 previous errors

File: runtime/src/snapshot_utils.rs [hunk 9]
```diff
@@ -1821,6 +1916,15 @@ pub fn get_highest_incremental_snapshot_archive_slot(
     .map(|incremental_snapshot_archive_info| incremental_snapshot_archive_info.slot())
 }
 
+/// Get the full snapshot with the highest slot in a directory
+/// Assume every bank snapshot directory is a full snapshot for now.  Will support incremental sanpshot
+/// later.
+pub fn get_highest_bank_snapshot(snapshots_dir: impl AsRef<Path>) -> Result<BankSnapshotInfo> {
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: 1.  Moved the function up;
2. Changed to return Option;
3. It is used in a test which verifies the checks in this PR, so it is needed here.

File: runtime/src/snapshot_utils.rs [hunk 10]
```diff
@@ -296,7 +325,34 @@ pub enum SnapshotError {
...
+    #[error("missing version file {}", .0.display())]
+    MissingVersionFile(PathBuf),
+
+    #[error("invalid snapshot version")]
+    InvalidVersion,
+
+    #[error("snapshot directory incomplete {}", .0.display())]
+    DirIncomplete(PathBuf),
+
+    #[error("missing snapshotfile {}", .0.display())]
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: fixed

File: runtime/src/snapshot_utils.rs [hunk 11]
```diff
@@ -296,7 +325,34 @@ pub enum SnapshotError {
...
+    MissingStatusCacheFile(PathBuf),
+
+    #[error("missing version file {}", .0.display())]
+    MissingVersionFile(PathBuf),
+
+    #[error("invalid snapshot version")]
+    InvalidVersion,
+
+    #[error("snapshot directory incomplete {}", .0.display())]
+    DirIncomplete(PathBuf),
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: fixed

File: runtime/src/snapshot_utils.rs [hunk 12]
```diff
@@ -1821,6 +1916,15 @@ pub fn get_highest_incremental_snapshot_archive_slot(
     .map(|incremental_snapshot_archive_info| incremental_snapshot_archive_info.slot())
 }
 
+/// Get the full snapshot with the highest slot in a directory
+/// Assume every bank snapshot directory is a full snapshot for now.  Will support incremental sanpshot
+/// later.
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: Fixed

**Comment by xiangzhu70** [comment]
> Can you link me to the code you're referring to, please? I'm not finding other code that calls `get_bank_snapshots()` other than in `snapshot_utils.rs` or tests.

test_bank_fields_from_snapshot 
I debugged that failure,  added the function fill_snapshot_meta_files_for_unarchived_snapshot so that this test can pass.  You can break at get_bank_snapshots() when running this test to see how it returns no snapshot without that fix.

**Comment by xiangzhu70** [comment]
> since a snapshot archive is different from a bank snapshot, it seems incorrect to call `BankSnapshotInfo::new_from_dir()` on it.

But it is the existing code on archive test which calls get_bank_snapshots to get back Vec<BankSnapshotInfo>.  It is just the shared operation to get back snapshot info from a directory, regardless of whether the directory is from the operation snapshot directory, or an unpacked directory from an archive.  It looks fine to me.  Could you clarify how you want it to be fixed?

**Comment by xiangzhu70** [comment]
> Is it correct to say that calling `fill_snapshot_meta_files_for_unarchived_snapshot()` in `unarchive_snapshot()` was added to fix one test?

Yes.  it fixes test_bank_fields_from_snapshot

File: runtime/src/snapshot_utils.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:332]: No, PartialEq doesn't work either.

```
error[E0369]: binary operation `==` cannot be applied to type `std::io::Error`
   --> runtime/src/snapshot_utils.rs:335:16
    |
332 | #[derive(Error, Debug, PartialEq)]
    |                        --------- in this derive macro expansion
...
335 |     Io(#[from] std::io::Error),
    |                ^^^^^^^^^^^^^^
    |
    = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0369`.
error: could not compile `solana-runtime` due to previous error

File: runtime/src/snapshot_utils.rs [hunk 13]
```diff
@@ -296,7 +325,34 @@ pub enum SnapshotError {
 
     #[error("invalid AppendVec path: {}", .0.display())]
     InvalidAppendVecPath(PathBuf),
+
+    #[error("no valid snapshot dir found under {}", .0.display())]
+    NoSnapshotSlotDir(PathBuf),
+}
+#[derive(Error, Debug)]
+pub enum SnapshotNewFromDirError {
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:336]: done.

**Comment by xiangzhu70** [comment]
> it makes sense to me to have two different functions for getting the bank snapshot within their respective contexts, returning each's pertinent information.

I think it depends on the perception.  If the perception is that there are two kinds of snapshots, one in the operation directory, one from archive, then here are two different contexts asking for two different functions.  Another perception is an archive contains a snapshot, a snapshot unpacked from an archive is still a snapshot just like  one from the operation directory.  Then the same function applies to that snapshot regardless of its source. 

If we follow the 1st perception, the function in the unarchiving context will need to avoid passing BankSnapshotInfo (if that struct is associated only with a snapshot in operation), but the logic about finding the directory and then the file in it would be duplicated.  Not sure if it is needed.

I think the first perception is fine in theory, because we can think a snapshot (a full state in directory) goes in and out of an archive.  But the tricky part is that we don't want to change the existing archive format for compatibility reason, so we are not really adding the full state into the archive, but instead hacking it to a full state snapshot dir when unpacking it.

Anyway, in the long term, I believe the clean way would be to always to split the flow into two pipeline stages:
 1. unpack an archive to a bank snapshot directory, 
 2. construct a bank from the snapshot directory.  
 So the code of constructing a bank directly from an archive probably does not matter much.

File: runtime/src/snapshot_utils.rs [hunk 14]
```diff
@@ -4503,4 +4621,59 @@ mod tests {
...
         assert!(matches!(ret, Err(SnapshotError::InvalidAppendVecPath(_))));
     }
+
+    #[test]
+    fn test_get_highest_bank_snapshot() {
+        solana_logger::setup();
+
+        let genesis_config = GenesisConfig::default();
+        let bank0 = Bank::new_for_tests(&genesis_config);
+        let mut bank_forks = BankForks::new(bank0);
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:4631]: I am using bank_forks to keep the banks, so I can loop to set up multiple banks.  

I had trouble looping over banks, and updating the local bank variable to point to the next bank.  I looked through the code and found an example using BankForks.  Not sure if there is a better way.

File: runtime/src/snapshot_utils.rs [hunk 15]
```diff
@@ -1529,6 +1599,39 @@ fn streaming_unarchive_snapshot(
         .collect()
 }
 
+/// BankSnapshotInfo::new_from_dir() requires a few meta files to accept a snapshot dir
+/// as a valid one.  A dir unpacked from an archive lacks these files.  Fill them here to
+/// allow new_from_dir() checks to pass.  These checks are not needed for unpacked dirs,
+/// but it is not clean to add another flag to new_from_dir() to skip them.
+fn fill_snapshot_meta_files_for_unarchived_snapshot(unpack_dir: impl AsRef<Path>) -> Result<()> {
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: updated

File: runtime/src/snapshot_utils.rs [hunk 16]
```diff
@@ -1529,6 +1599,39 @@ fn streaming_unarchive_snapshot(
...
+        return Err(SnapshotError::NoSnapshotSlotDir(snapshots_dir));
+    }
+
+    // The unpacked dir has a single slot dir, which is the snapshot slot dir.
+    let slot_dir = fs::read_dir(&snapshots_dir)
+        .unwrap()
+        .find(|entry| entry.as_ref().unwrap().path().is_dir())
+        .unwrap()
+        .unwrap()
+        .path();
```
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs]: replaced unwrap with map_err and ok_or_else

File: runtime/src/snapshot_utils.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (xiangzhu70) [reply runtime/src/snapshot_utils.rs:4631]: Great!  thanks!  It works.
