### ISSUE TITLE
`let...else` statements are unstable in  solana-frozen-abi-macro-1.16.0

### ISSUE THREAD

**Issue by D0bhareach** [solana-labs/solana#32133]
#### Problem

While compiling anchor-lang = "0.28.0" project have got this error:
.cargo/registry/src/github.com-1ecc6299db9ec823/solana-frozen-abi-macro-1.16.0/src/lib.rs:422:5
   
422      let Some(expected_digest) = expected_digest else {
423           return Error::new_spanned(
424              TokenStream2::from(item),
425              "the required \"digest\" = ... attribute is missing.",
...
428          .into()
429      };
   
    = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information
    = help: add `#![feature(let_else)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `solana-frozen-abi-macro` due to previous error
My rustc -V: rustc 1.70.0 (90c541806 2023-05-31)

**Comment by Twist96** [comment]
I'm having this error too

**Comment by PratikBodawala** [comment]
I had the same issue, for now, I have downgraded the Rust version to 1.69.0

**Comment by sausage-dog** [comment]
I get this error with either Solana 1.16.1 or 1.16.0 at rustc 1.69.0.

**Comment by smart-tech-master** [comment]
me too

**Comment by mvines** [comment]
@dmakarov - not sure if you have any idea as to what's going on here? The bug reports so far are super low quality here but seems like there's something not right. Unclear if this is an anchor issue or something with the platform tooling

**Comment by D0bhareach** [comment]
This is issue with Rust  version used by  libraries I believe it  is 1.61 for Solana, honestly don't remember where remember it was in dependencies for workspace. So, I guess,  newer syntax is used to compile with older version. So if  code above is changed to to `if let Some(val) {bla-bla} else {bla-bla }` error should disappear.

**Comment by dmakarov** [comment]
> @dmakarov - not sure if you have any idea as to what's going on here? The bug reports so far are super low quality here but seems like there's something not right. Unclear if this is an anchor issue or something with the platform tooling

We'll update platform-tools to latest rust version soon. Until then we could patch frozen-abi-macro/src/lib.rs and add `#![feature(let_else)]` to enable  https://github.com/solana-labs/solana/blob/42aa5d243c89967f8fbc0185b5bb3bd1937c547d/frozen-abi/macro/src/lib.rs#L422  I haven't check that it would work with the platform-tools rust compiler, though.

**Comment by sausage-dog** [comment]
Works for me with this:

            ```
[dependencies]
            anchor-lang = "0.26.0"
            anchor-spl = "0.26.0"
            metaplex-token-metadata = { version = "0.0.1", features = ["no-entrypoint"] }
            solana-program = "=1.14.13"
            getrandom = { version = "0.2.9", features = ["custom"] }
            switchboard-v2 = "0.1.15"
            mpl-bubblegum = { version = "0.8.0", features = [ "no-entrypoint" ]}
            spl-account-compression = { version = "0.1.10", features = [ "no-entrypoint" ]}
```


at 

`rustc 1.69.0 (84c898d65 2023-04-16)`

**Comment by marshallr12** [comment]
This isn't an anchor specific issue. I can reproduce it attempting to build using rust 1.70 and dependency solana-program 1.16.1:

```
cargo new test-solana
cd test-solana
cargo add solana-program
cargo build-sbf
```
Compiling solana-frozen-abi-macro v1.16.1
error[E0658]: `let...else` statements are unstable
   --> /home/marshall/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-frozen-abi-macro-1.16.1/src/lib.rs:422:5
    |
422 | /     let Some(expected_digest) = expected_digest else {
423 | |         return Error::new_spanned(
424 | |             TokenStream2::from(item),
425 | |             "the required \"digest\" = ... attribute is missing.",
...   |
428 | |         .into()
429 | |     };
    | |______^
    |
    = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information
    = help: add `#![feature(let_else)]` to the crate attributes to enable

**Comment by mvines** [comment]
> cargo new test-solana --lib
> cd test-solana
> cargo add solana-program
> cargo build-sbf

These STR worked fine for me.

```
$ cargo build-sbf --version
solana-cargo-build-sbf 1.16.1
platform-tools v1.37
```

**Comment by dmakarov** [comment]
platform-tools 1.37 is based on rust 1.68. `let_else` feature is stable since rust 1.65, so, indeed, platform-tools v1.37 should work.

**Comment by mvines** [comment]
I can also confirm the issue reproduces with:
```
$ cargo build-sbf --version
solana-cargo-build-sbf 1.14.17
sbf-tools v1.29
```

But this is also expected. One cannot expect to build solana-program 1.16.1 with the platform tools in 1.14

**Comment by mvines** [comment]
We could try adding https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field to crates like solana-program to make this error more explicit

**Comment by marshallr12** [comment]
As of now, if I run `solana-install update`, I will get solana-cargo-build-sbf 1.14.20 and sbf v1.29, which still reproduces the issue if you follow the [Rust Quickstart](https://docs.solana.com/getstarted/rust ).

**Comment by mvines** [comment]
`solana-install update` will (intentionally) not bump your minor solana version, so if you are currently on a v1.14 release then you won't get v1.16. Use `solana-install init v1.16.1` to jump to a v1.16 release.

**Comment by marshallr12** [comment]
> `solana-install update` will (intentionally) not bump your minor solana version, so if you are currently on a v1.14 release then you won't get v1.16. Use `solana-install init v1.16.1` to jump to a v1.16 release.

Thank you, that worked for me. I think it would be very useful to have a `--latest`  or similar option for `solana-install update`.

**Comment by mvines** [comment]
Great. Hopefully starting with 1.16.2, we'll have a more explicit error when this condition occurs so it'll be more obvious that a newer version of the platform-tools needs to be installed.
